version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node
        environment:
          PIPENV_VENV_IN_PROJECT: true
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ''
    steps:
      - checkout
      - run: mkdir test-reports
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv 
            pipenv install --dev
            sudo npm install yarn -g
            yarn install 
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - 'venv'
      - run:
          command: |
            pipenv run pytest
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/